services:

  postgres:
    image: postgres:17
    container_name: kycflow-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kycflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kycflow-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend

    container_name: kycflow-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/kycflow

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

  worker:
    build:
      context: ./backend

    container_name: kycflow-worker

    command: npm run worker:prod

    env_file:
      - ./backend/.env

    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/kycflow

    depends_on:
      - redis
      - postgres

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: