export * from "./reviewerAssigned.template";
export * from "./applicationApproved.template";
export * from "./applicationRejected.template";
export * from "./reviewerReminder.template";
export * from "./escalation.template";
export * from "./dailySummary.template";
export * from "./otp.template";
export * from "./invitation.template";
export * from "./applicantApproved.template";